title: xoxown31
description: portfolio & blog
theme: just-the-docs
url: "https://xoxown31.github.io"

just_the_docs:
  color_scheme: dark
  aux_links:
    GitHub: https://github.com/xoxown31/xoxown31.github.io